apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
